# Generated by Django 5.2.10 on 2026-06-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='book',
            new_name='catalog_boo_slug_7fab6a_idx',
            old_name='catalog_boo_slug_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='catalog_boo_isbn_43f845_idx',
            old_name='catalog_boo_isbn_456def_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='catalog_boo_is_acti_77f529_idx',
            old_name='catalog_boo_is_acti_789ghi_idx',
        ),
    ]
