# Generated by Django 5.2.10 on 2026-06-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_boo_slug_123abc_idx_catalog_boo_slug_7fab6a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
