# Generated by Django 5.2.10 on 2026-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
