# Generated by Django 5.2.10 on 2026-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='django_2.jpg', upload_to='books/pdfs/'),
        ),
    ]
