# Generated by Django 5.2.10 on 2026-06-24 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rolerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='id_document',
            field=models.FileField(upload_to='role_requests/'),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='requested_role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('course_rep', 'Course Rep'), ('vendor', 'Vendor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
