# Generated by Django 5.2.10 on 2026-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rolerequest_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='id_document',
            field=models.ImageField(upload_to='role_requests/'),
        ),
    ]
