# Generated by Django 5.2.10 on 2026-06-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rolerequest_requested_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
