# Generated by Django 5.2.10 on 2026-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('faculty', models.TextField(max_length=100)),
                ('department', models.TextField(max_length=100)),
                ('id_document', models.FileField(upload_to='lecturer/')),
            ],
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('vendor_experience', models.TextField()),
                ('host_reasons', models.TextField()),
                ('id_document', models.FileField(upload_to='vendor/')),
            ],
        ),
    ]
