# Generated by Django 5.2.10 on 2026-06-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lecturerrequest_vendorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerrequest',
            name='declined_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturerrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lecturerrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='declined_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
