# Generated by Django 5.2.10 on 2026-06-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rolerequest_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='role_requests/'),
        ),
    ]
