# Generated by Django 5.2.10 on 2026-06-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rolerequest_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
