# Generated by Django 5.2.10 on 2026-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_rolerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
